#!/bin/bash

#
# Often in development mode, we retrieve a database from a production server
# using 'attachment_s3' (cloud platform). This script automatically changes
# the attachments to  be stored in the database because there is no S3 bucket
# when working in dev.
#
# When one needs to work on S3 with a development instance, he might set the
# ODOO_DEV_KEEP_ATTACHMENT_S3=true environment variable
#

keep_location=$(echo "${ODOO_DEV_KEEP_ATTACHMENT_S3}" | tr '[:upper:]' '[:lower:]' )

if [ "$keep_location" = "true" ]; then
  exit 0
fi

if [ "$RUNNING_ENV" = "dev" ] ; then
  echo "Setting ir_attachment.location parameter to 'db' if the current is 's3'"
  psql --quiet -h db << EOF

  UPDATE ir_config_parameter
  SET value = 'db'
  WHERE key = 'ir_attachment.location'
  AND value = 's3';

EOF
fi
